vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|29 Feb 2012 23:41:54 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|MarcSMith-PC\\Marc SMith
vti_modifiedby:SR|MarcSMith-PC\\Marc SMith
vti_timecreated:TR|29 Feb 2012 23:41:54 -0000
vti_cacheddtm:TX|29 Feb 2012 23:41:54 -0000
vti_filesize:IR|5479
vti_cachedtitle:SR| <?php if ( is_home() ) { ?><?php bloginfo('name'); ?> | <?php bloginfo('description'); ?><?php } ?> <?php if ( is_search() ) { ?><?php bloginfo('name'); ?> | <?php _e('Search Results', 'cp'); ?><?php } ?> <?php if ( is_404() ) { ?><?php bloginfo('name'); ?> | <?php _e('404 Nothing Found', 'cp');?><?php } ?> <?php if ( is_author() ) { ?><?php bloginfo('name'); ?> | <?php _e('Author Archives', 'cp'); ?><?php } ?> <?php if ( is_single() ) { ?><?php wp_title(''); ?> | <?php bloginfo('name'); ?><?php } ?> <?php if ( is_page() ) { ?><?php bloginfo('name'); ?> | <?php wp_title(''); ?><?php } ?> <?php if ( is_category() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php single_cat_title(); ?><?php } ?> <?php if ( is_month() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php the_time(__('F', 'cp')); ?><?php } ?> <?php if ( is_day() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php the_time(__('F j, Y', 'cp')); ?><?php } ?> <?php if (function_exists('is_tag')) { if ( is_tag() ) { ?><?php bloginfo('name'); ?> | <?php _e('Tag Archive', 'cp'); ?> | <?php single_tag_title("", true); } } ?> 
vti_cachedbodystyle:SR|<body <?php body_class(); ?> >
vti_cachedlinkinfo:VX|D|http://sopastrike.com/strike H|< Q|< Q|< H|< H|< H|https://www.facebook.com/OccupyDC S|< H|https://www.twitter.com/Occupy_DC S|< H|https://plus.google.com/112483678724979264653/posts S|< H|http://occupywashdc.tumblr.com S|< H|http://www.reddit.com/r/occupyDC S|< H|https://www.twitter.com/OccupyKst S|< H|http://www.flickr.com/groups/occupydc/ S|< H|http://www.youtube.com/user/occupytv S|< H|http://vimeo.com/channels/occupydc S|< H|http://occupydc.org/feed S|< H|< S|< K|header.php
vti_cachedsvcrellinks:VX|NDHS|http://sopastrike.com/strike DHUS|wp-content/themes/occupydc-v10/< DQUS|wp-content/themes/occupydc-v10/< DQUS|wp-content/themes/occupydc-v10/< DHUS|wp-content/themes/occupydc-v10/< DHUS|wp-content/themes/occupydc-v10/< NHSS|https://www.facebook.com/OccupyDC DSUS|wp-content/themes/occupydc-v10/< NHSS|https://www.twitter.com/Occupy_DC DSUS|wp-content/themes/occupydc-v10/< NHSS|https://plus.google.com/112483678724979264653/posts DSUS|wp-content/themes/occupydc-v10/< NHHS|http://occupywashdc.tumblr.com DSUS|wp-content/themes/occupydc-v10/< NHHS|http://www.reddit.com/r/occupyDC DSUS|wp-content/themes/occupydc-v10/< NHSS|https://www.twitter.com/OccupyKst DSUS|wp-content/themes/occupydc-v10/< NHHS|http://www.flickr.com/groups/occupydc/ DSUS|wp-content/themes/occupydc-v10/< NHHS|http://www.youtube.com/user/occupytv DSUS|wp-content/themes/occupydc-v10/< NHHS|http://vimeo.com/channels/occupydc DSUS|wp-content/themes/occupydc-v10/< NHHS|http://occupydc.org/feed DSUS|wp-content/themes/occupydc-v10/< DHUS|wp-content/themes/occupydc-v10/< DSUS|wp-content/themes/occupydc-v10/< FKUS|wp-content/themes/occupydc-v10/header.php
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=content-type <?php\\ bloginfo('html_type')\\ ?>;\\ charset=<?php\\ bloginfo('charset')\\ ?> description <?php\\ bloginfo('description')\\ ?> language <?php\\ echo\\ get_bloginfo('language');\\ ?>
vti_charset:SR|utf-8
vti_title:SR| <?php if ( is_home() ) { ?><?php bloginfo('name'); ?> | <?php bloginfo('description'); ?><?php } ?> <?php if ( is_search() ) { ?><?php bloginfo('name'); ?> | <?php _e('Search Results', 'cp'); ?><?php } ?> <?php if ( is_404() ) { ?><?php bloginfo('name'); ?> | <?php _e('404 Nothing Found', 'cp');?><?php } ?> <?php if ( is_author() ) { ?><?php bloginfo('name'); ?> | <?php _e('Author Archives', 'cp'); ?><?php } ?> <?php if ( is_single() ) { ?><?php wp_title(''); ?> | <?php bloginfo('name'); ?><?php } ?> <?php if ( is_page() ) { ?><?php bloginfo('name'); ?> | <?php wp_title(''); ?><?php } ?> <?php if ( is_category() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php single_cat_title(); ?><?php } ?> <?php if ( is_month() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php the_time(__('F', 'cp')); ?><?php } ?> <?php if ( is_day() ) { ?><?php bloginfo('name'); ?> | <?php _e('Archive', 'cp'); ?> | <?php the_time(__('F j, Y', 'cp')); ?><?php } ?> <?php if (function_exists('is_tag')) { if ( is_tag() ) { ?><?php bloginfo('name'); ?> | <?php _e('Tag Archive', 'cp'); ?> | <?php single_tag_title("", true); } } ?> 
vti_backlinkinfo:VX|wp-content/themes/occupydc-v10/header.php
